repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: sort-simple-yaml
      - id: end-of-file-fixer
        types: [non-executable, file, text]
        exclude: ^site
      - id: trailing-whitespace
        exclude: ^site
        types: [non-executable, file, text]



  - repo: https://github.com/psf/black
    rev: 21.5b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

  - repo: local
    hooks:
      - id: test
        name: unit tests
        language: system
        entry: pdm run test -m 'not slow'
        pass_filenames: false
