[project]
name = "composer"
version = "0.1.0"
description = ""
authors = [
    {name = "Stephan Fitzpatrick", email = "knowsuchagency@gmail.com"},
]
dependencies = [
    "aws-cdk.core",
    "aws-cdk.aws_events",
    "aws-cdk.aws_events_targets",
    "aws-cdk.aws_lambda_python",
    "aws-cdk.aws_stepfunctions_tasks",
]
requires-python = ">=3.8"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pdm.scripts]
_.env_file = ".env"

synth = "cdk synth"
deploy = "cdk deploy --verbose"
destroy = "cdk destroy"

[tool.pdm.dev-dependencies]
dev = [
    "loguru~=0.5",
]
