[project]
authors = [
  {name = "Stephan Fitzpatrick", email = "knowsuchagency@gmail.com"},
]
dependencies = []
description = "For orchestration using AWS Step Functions"
dynamic = ["classifiers"]
keywords = ["orchestration", "aws", "cloud"]
license = {text = "MIT"}
name = "orkestra"
requires-python = ">=3.8"
version = "0.2.0"

[project.urls]
Repository = "https://github.com/knowsuchagency/composer"
homepage = "https://github.com/knowsuchagency/composer"

[project.optional-dependencies]
cdk = [
  "aws-cdk.core",
  "aws-cdk.aws_events",
  "aws-cdk.aws_events_targets",
  "aws-cdk.aws_lambda_python",
  "aws-cdk.aws_stepfunctions_tasks",
]

[build-system]
build-backend = "pdm.pep517.api"
requires = ["pdm-pep517"]

[tool.pdm.scripts]
_.env_file = ".env"

synth = "cdk synth"

deploy.shell = """
set -ex
cdk deploy --verbose --require-approval=never
klaxon --title orkestra --subtitle deployed
"""

destroy.shell = """
set -ex
cdk destroy --force
klaxon --title orkestra --subtitle destroyed
"""

test-publish = "twine upload --repository testpypi dist/*"

publish.shell = """

twine upload dist/*
"""

pub.shell = """
set -x
pdm build
pdm run test-publish
pdm run publish
"""

[tool.pdm.dev-dependencies]
dev = [
  "loguru~=0.5",
  "klaxon",
]
