name: test

on: push

jobs:

  test:

    environment: dev

    env:
      POWERTOOLS_TRACE_DISABLED: 1
      ENVIRONMENT: dev

    strategy:
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v2

      - uses: pdm-project/setup-pdm@v2
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          prerelease: true
          enable-pep582: true

      - name: Install dependencies
        run: pdm install -s :all

      - name: Run Unit Tests
        run: pdm run test # -m 'not synthesis'
