name: test

on: push

jobs:

  environment: dev

  test:

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: pdm-project/setup-pdm@v2
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          prerelease: true
          enable-pep582: true

      - name: Install dependencies
        run: pdm install -s :all

      - name: Run Unit Tests
        run: pdm run test
